### ISSUE TITLE
lib usage

### ISSUE THREAD

**Issue by rohybnol** [cutecatsandvirtualmachines/SKLib#1]
how to use compiled sklib.lib in driver, is there any sort of documentation maybe? great project!

oh as well using your zydis vcpkg there is 2 undefined symbols:
ZYDIS_ADDRESS_WIDTH_64 and ZydisDecoderDecodeBuffer inside GPUSpoof

**Comment by cutecatsandvirtualmachines** [comment]
There's a vcpkg.json, so you need to run
`vcpkg install`
inside a vs command prompt and it will do its thing

**Comment by rohybnol** [comment]
yea thats what i did however it has 2 undefined symbols

**Comment by cutecatsandvirtualmachines** [comment]
What compilation target are you using? With or without spoofer. Also are you compiling the whole solution?

**Comment by rohybnol** [comment]
release x64 with spoofer, intel, compiling whole solution, compiles fine when commenting out said code, so its only these 2 undefined symbols.
i try understand how to use said lib in my own kernel driver

**Comment by cutecatsandvirtualmachines** [comment]
It's because for some reason it's using a wrong zydis version. The symbols I use are removed in the latest versions so you need older commits. 

The zydis I have currently installed has:
`#define ZYDIS_VERSION (ZyanU64)0x0003000100000000`

**Comment by cutecatsandvirtualmachines** [comment]
Using the library in your kernel driver is like using any other library. Add lib to libraries for linkage and add include headers in your project.

**Comment by rohybnol** [comment]
what is a library director tho?

**Comment by cutecatsandvirtualmachines** [comment]
You need to google "How to use library C/C++"

**Comment by rohybnol** [comment]
I am familiar with its usage and have correctly included the necessary files in the SKLib\SKLib-v\include directory. However, when attempting to compile using the spoofer::SpoofAll() function, I encounter a compiler error indicating that cpp.h cannot be found, despite it being present in SKLib. I attempted to resolve the issue manually, but there appear to be additional complications.
