### ISSUE TITLE
LNK2001 Error when trying to use SKLib

### ISSUE THREAD

**Issue by bphucc** [cutecatsandvirtualmachines/SKLib#2]
I'm attempting to integrate SKLib into my driver, but when testing the code, I encounter this error:

![image](https://github.com/user-attachments/assets/a195b161-70bc-443e-92ac-8588eb7e797f)

I've already included the include directories, as well as the library directory, but this error persists, any suggestions?

**Comment by cutecatsandvirtualmachines** [comment]
You need to add SKLib to the list of libraries the project needs. SKLib.lib is not being linked to your driver.

**Comment by bphucc** [comment]
I've already included it, I think so: 
![image](https://github.com/user-attachments/assets/312df533-dc6d-4673-ba96-a8dc00a73161)
![image](https://github.com/user-attachments/assets/c475710a-e8ca-4f25-ad58-24d1d6e67ba5)

**Comment by cutecatsandvirtualmachines** [comment]
Check that you included the library in the current compilation target configuration (ex. ReleaseWithSpoofer or Release).

**Comment by cutecatsandvirtualmachines** [comment]
Also you would usually include SKLib-v to have access to everything at once.

**Comment by bphucc** [comment]
I did the same thing what you said, and it stills: 
![image](https://github.com/user-attachments/assets/2d2480ee-583f-4599-ada7-8fc4eb04f895)

**Comment by cutecatsandvirtualmachines** [comment]
Why do you define DriverEntry as EXTERN_C? How is a C method expected to see a C++ definition?

**Comment by bphucc** [comment]
I'm planning to  have some headers defining the native structs of Windows, so extern C is used to avoid the error from those (I tried to put out the extern C but it keeps fail)

**Comment by cutecatsandvirtualmachines** [comment]
Highly unsure what you're doing with this project, but fyi C methods or compilation targets can NOT see C++ definitions, therefore you'll always get undefined symbols. 
Not even sure what part of "native structs for Windows" would require DriverEntry to be extern C.

**Comment by bphucc** [comment]
I understand.

But I've just removed all the C methods, but the problem still persists. I'm just not sure and just want to testing out the functionalities of this lib.

**Comment by bphucc** [comment]
Alright, thank you!
